name: "Python Pipenv Action"
author: "@tiagovrtr"
description: "An action to run https://github.com/pypa/pipenv"
branding:
  icon: "truck"
  color: "gray-dark"
inputs:
  pipenv-version:
    description: "The version of pipenv to install"
    required: true
    default: "2022.9.21"
runs:
  using: "composite"
  steps:
    - run: |
        pip install pipenv==${{ inputs.pipenv-version }}
      shell: bash
