name: "Python Poetry Action"
author: "@abatilo"
description: "An action to run https://github.com/python-poetry/poetry"
branding:
  icon: "truck"
  color: "gray-dark"
inputs:
  poetry-version:
    description: "The version of poetry to install"
    required: true
    default: "1.1.3"
runs:
  using: "composite"
  steps:
    - run: |
        curl -sSl -vvv https://raw.githubusercontent.com/python-poetry/poetry/${{ inputs.poetry-version }}/get-poetry.py | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      shell: bash
