name: 'Python Poetry Action'
author: '@abatilo'
description: 'An action to run https://github.com/python-poetry/poetry'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'truck'
  color: 'gray-dark'
inputs:
  python_version:
    description: 'The version of python to install'
    required: true
    default: '3.8'
  poetry_version:
    description: 'The version of poetry to install'
    required: true
    default: '1.0'
  working_directory:
    description: 'The directory to run poetry commands in.'
    required: false
    default: '.'
