name: "Python Poetry Action"
author: "@abatilo"
description: "An action to run https://github.com/python-poetry/poetry"
branding:
  icon: "truck"
  color: "gray-dark"
inputs:
  poetry-version:
    description: "The version of poetry to install"
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - if: ${{ inputs.poetry-version == 'latest' }}
      run: |
        pip install -U poetry
      shell: bash
    - if: ${{ inputs.poetry-version != 'latest' }}
      run: |
        pip install poetry==${{ inputs.poetry-version }}
      shell: bash
