name: "Python Poetry Action"
author: "@abatilo"
description: "An action to run https://github.com/python-poetry/poetry"
branding:
  icon: "truck"
  color: "gray-dark"
inputs:
  poetry-version:
    description: "The version of poetry to install"
    required: false
    default: "latest"
  poetry-plugins:
    description: "The whitespace/newline-separated list of poetry plugins to install."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - if: ${{ inputs.poetry-version == 'latest' }}
      run: |
        pipx install poetry
      shell: bash
    - if: ${{ inputs.poetry-version == 'main' }}
      run: |
        pipx install git+https://github.com/python-poetry/poetry.git@main
      shell: bash
    - if: ${{ inputs.poetry-version != 'latest' && inputs.poetry-version != 'main' }}
      run: |
        pipx install poetry==${{ inputs.poetry-version }}
      shell: bash
    - run: |
        pipx ensurepath
      shell: bash
    - if: ${{ inputs.poetry-plugins != '' }}
      run: |
        ALL_PLUGINS=$(echo "${{ inputs.poetry-plugins }}")
        for PLUGIN in $ALL_PLUGINS; do
          poetry self add $PLUGIN
        done
      shell: bash
