name: 'Python Poetry Github Action'
author: '@tokusumi'
description: 'An action to run https://github.com/python-poetry/poetry'

branding:
  icon: 'truck'
  color: 'gray-dark'
inputs:
  python_version:
    description: 'The version of python to install'
    required: true
    default: '3.8'
  poetry_version:
    description: 'The version of poetry to install'
    required: true
    default: '1.0.0'
  working_directory:
    description: 'The directory to run poetry commands in.'
    required: false
    default: '.'
  command:
    description: 'The command for poetry'
    repuired: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - 'privileged'
